name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build images with docker-compose
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          ORIGIN_PEM: ${{ secrets.ORIGIN_PEM }}
          PRIVATEKEY_PEM: ${{ secrets.PRIVATEKEY_PEM }}
        run: |
          docker compose build
        
      # Prepare secrets for frontend build (PEM files)
      - name: Write PEM secrets
        run: |
          echo "${{ secrets.ORIGIN_PEM }}" > origin.pem
          echo "${{ secrets.PRIVATEKEY_PEM }}" > privatekey.pem

      # Push frontend image
      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tariffic-frontend:latest

      # Push backend image
      - name: Push backend image
        run: docker push ${{secrets.DOCKER_USERNAME}}/tariffic-backend:latest

