name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          ORIGIN_PEM: ${{ secrets.ORIGIN_PEM }}
          PRIVATEKEY_PEM: ${{ secrets.PRIVATEKEY_PEM }}
          NGINX_CONF: ${{ secrets.NGINX_CONF }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Prepare secrets
        run: |
          mkdir -p secrets
          echo "$ORIGIN_PEM" > secrets/origin.pem
          echo "$PRIVATEKEY_PEM" > secrets/privatekey.pem
          echo "$NGINX_CONF" > secrets/nginx.conf

      # Build backend image
      - name: Build and push backend
        run: |
          export DOCKER_BUILDKIT=1
          docker build \
            --secret id=origin.pem,src=secrets/origin.pem \
            --secret id=privatekey.pem,src=secrets/privatekey.pem \
            -t $DOCKER_USERNAME/tariffic-backend:latest ./backend
          docker push $DOCKER_USERNAME/tariffic-backend:latest

      # 5️⃣ Build frontend image with nginx secret
      - name: Build and push frontend
        run: |
          export DOCKER_BUILDKIT=1
          docker build \
            --secret id=nginx.conf,src=secrets/nginx.conf \
            -t $DOCKER_USERNAME/tariffic-frontend:latest ./frontend
          docker push $DOCKER_USERNAME/tariffic-frontend:latest


